apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    k8s-app: kube-proxy-amd64
  name: kube-proxy-amd64
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: kube-proxy-amd64
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/tolerations: '[{"key":"dedicated","value":"master","effect":"NoSchedule"}]'
      creationTimestamp: null
      labels:
        k8s-app: kube-proxy-amd64
    spec:
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      containers:
      - command:
        - kube-proxy
        - --kubeconfig=/var/lib/kube-proxy/kubeconfig.conf
        image: gcr.io/google_containers/kube-proxy-amd64:v1.6.0-alpha.1
        imagePullPolicy: IfNotPresent
        name: kube-proxy-amd64
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/kube-proxy
          name: kube-proxy
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      schedulername: default-scheduler
      securityContext: {}
      serviceAccount: kube-proxy
      serviceAccountName: kube-proxy
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: kube-proxy
        name: kube-proxy
